language: rust
osx_image: xcode10

git:
  submodules: true

os:
  - osx

rust:
  - stable
  - nightly

cache: cargo

before_script:
  - sudo gem install xcpretty

script:
  - xcodebuild clean test -scheme XiEditor | xcpretty -s
  # - cd rust
  # - export CARGO_TARGET_DIR=/tmp/target
